[manager]
show_hidden = true
sort_by = "natural"

[preview]
# Ueberzugpp — лучший выбор для Hyprland/Wayland
preview_method = "ueberzug"
max_width = 1200
max_height = 1200

[opener]
edit = [{ run = 'nvim "$@"', block = true }]
play = [{ run = 'mpv "$@"', orphan = true }]

