engine: mpv
token: y0_AgAAAAB2F_LbAAG8XgAAAAEU1HYMAAC9XK5xaFlGzYVhruTeScgvmNGP7A
buffer-size-ms: 80
rewind-duration-s: 5
volume: 0.6000000000000001
volume-step: 0.05
suppress-errors: false
show-lyrics: true
cache-tracks: likes
cache-dir: ""
search:
    artists: true
    albums: false
    playlists: false
controls:
    quit: ctrl+q,ctrl+c
    apply: enter
    cancel: esc
    cursor-up: up
    cursor-down: down
    reload: ctrl+\
    show-all-kyes: '?'
    playlists-up: ctrl+up
    playlists-down: ctrl+down
    playlists-rename: ctrl+r
    playlists-hide: ctrl+b
    tracks-like: l
    tracks-add-to-playlist: a
    tracks-remove-from-playlist: ctrl+a
    tracks-share: ctrl+s
    tracks-shuffle: ctrl+x
    tracks-search: ctrl+f
    tracks-hide: ctrl+t
    player-pause: ' '
    player-next: right
    player-previous: left
    player-rewind-forward: ctrl+right
    player-rewind-backward: ctrl+left
    player-like: L
    player-cache: S
    player-vol-up: +,=
    player-vol-down: '-'
    player-toggle-lyrics: t
    player-hide: ctrl+p
colors:
    accent: '#FC0'
    error: '#F33'
    background: '#6b6b6b'
    active-text: '#EEE'
    normal-text: '#CCC'
    inactive-text: '#888'
    lyrics-previous: '#444'
    lyrics-current: '#EEE'
    lyrics-next: '#777'
