[Video]
dub = ''
quality = 1080

[Providers]
autoSync = true

[Providers.domainMap]
anilib = 'api.cdnlibs.org'
animego = 'v2.animego.bz'
yummyanime = 'site.yummyani.me'

[Players]
syncInterval = '3d'
domains = [
  'aniboom.one',
  'video.sibnet.ru',
  'kodik.info',
  'vk.com',
  'alloha.yani.tv',
  'aksor.yani.tv'
]
